/* ═══════════════════════════════════════════════
   WaterfallChart - Type Definitions
   Domain interfaces, RenderConfig, literal unions
   ═══════════════════════════════════════════════ */

"use strict";

import powerbi from "powerbi-visuals-api";
import ISelectionId = powerbi.visuals.ISelectionId;

/* ── Literal unions (W1: as const + derived type) ── */

export const ORIENTATIONS = ["vertical", "horizontal"] as const;
export type Orientation = (typeof ORIENTATIONS)[number];

export const CONNECTOR_LINE_STYLES = ["solid", "dashed"] as const;
export type ConnectorLineStyle = (typeof CONNECTOR_LINE_STYLES)[number];

export const LABEL_POSITIONS = ["above", "inside", "auto"] as const;
export type LabelPosition = (typeof LABEL_POSITIONS)[number];

export const VALUE_FORMATS = ["auto", "number", "currency", "compact"] as const;
export type ValueFormat = (typeof VALUE_FORMATS)[number];

export const LEGEND_POSITIONS = ["top", "bottom"] as const;
export type LegendPosition = (typeof LEGEND_POSITIONS)[number];

export const X_LABEL_ROTATIONS = ["0", "45", "90"] as const;
export type XLabelRotation = (typeof X_LABEL_ROTATIONS)[number];

/** Classification of each waterfall bar (W2) */
export const BAR_TYPES = ["start", "increase", "decrease", "total"] as const;
export type BarType = (typeof BAR_TYPES)[number];

/* ── Domain model ── */

/** A single parsed row from the data view before waterfall computation */
export interface WaterfallRawItem {
    category: string;
    value: number;
    isTotal: boolean;
    selectionId: ISelectionId;
    tooltipExtras: TooltipExtra[];
    rowIndex: number;
}

/** Extra tooltip fields provided by the user */
export interface TooltipExtra {
    displayName: string;
    value: string;
}

/** A fully computed waterfall bar ready for rendering (W3) */
export interface WaterfallBar {
    category: string;
    value: number;
    barType: BarType;
    runningTotal: number;
    base: number;
    top: number;
    pctChangeFromPrevious: number | null;
    selectionId: ISelectionId | null;
    tooltipExtras: TooltipExtra[];
    rowIndex: number;
    isAutoGenerated: boolean;
}

/** Column index map from resolveColumns() */
export interface ColumnIndex {
    category: number;
    value: number;
    isTotal: number;
    tooltipFields: number[];
}

/* ── Render Config (W4: single bridge between formatting model and render) ── */

export interface RenderConfig {
    chart: {
        orientation: Orientation;
        barWidthFraction: number;
        barCornerRadius: number;
        showConnectorLines: boolean;
        connectorLineColor: string;
        connectorLineWidth: number;
        connectorLineStyle: ConnectorLineStyle;
    };
    colors: {
        increaseColor: string;
        decreaseColor: string;
        totalColor: string;
        startColor: string;
        selectedColor: string;
    };
    axis: {
        showXAxis: boolean;
        showYAxis: boolean;
        axisFontSize: number;
        axisFontColor: string;
        showGridlines: boolean;
        gridlineColor: string;
        xLabelRotation: XLabelRotation;
        showBaselineLine: boolean;
        baselineColor: string;
    };
    labels: {
        showValueLabels: boolean;
        labelPosition: LabelPosition;
        labelFontSize: number;
        labelFontColor: string;
        showRunningTotal: boolean;
        showPlusMinus: boolean;
        valueFormat: ValueFormat;
    };
    legend: {
        showLegend: boolean;
        legendPosition: LegendPosition;
        legendFontSize: number;
        legendFontColor: string;
    };
    summary: {
        autoStartTotal: boolean;
        autoEndTotal: boolean;
        endTotalLabel: string;
    };
}

/** Callbacks passed to render functions to decouple from Power BI APIs (W5) */
export interface ChartCallbacks {
    onBarClick: (bar: WaterfallBar, event: MouseEvent) => void;
    onBackgroundClick: () => void;
    onBarMouseOver: (bar: WaterfallBar, event: MouseEvent) => void;
    onBarMouseMove: (bar: WaterfallBar, event: MouseEvent) => void;
    onBarMouseOut: () => void;
}
